const cities={['Akron', 'Altoona', 'Camden', 'Albany', 'Arlington', 'Asheville',
       'Atlanta', 'Chicago', 'Atlantic City', 'Baltimore', 'Augusta',
       'Aurora', 'Bergen Co.', 'Battle Creek', 'Bay City', 'Belmont',
       'Binghamton/Johnson City', 'Boston', 'Birmingham', 'Braintree',
       'Detroit', 'Brockton', 'Bronx', 'Brookline', 'Brooklyn',
       'Cambridge', 'Canton', 'Charleston', 'Chattanooga', 'Charlotte',
       'Chelsea', 'Cleveland', 'Los Angeles', 'Denver', 'Columbus',
       'New Orleans', 'Dayton', 'Dallas', 'Decatur', 'Dedham',
       'East St. Louis', 'Erie', 'Duluth', 'Durham', 'Lake County Gary',
       'East Hartford', 'Elmira', 'Essex County', 'Lima', 'Fort Wayne',
       'Evansville', 'Fresno', 'Grand Rapids', 'Everett', 'Flint',
       'Queens', 'Greater Kansas City', 'Racine', 'Indianapolis',
       'Holyoke Chicopee', 'Hamilton', 'Hudson County', 'Greensboro',
       'Haverhill', 'Jacksonville', 'Johnstown', 'Joliet', 'Kalamazoo',
       'Kenosha', 'Knoxville', 'Lexington', 'Lorain',
       'Lower Westchester Co.', 'Louisville', 'Lynchburg', 'Miami',
       'Macon', 'New Haven', 'Madison', 'Malden', 'Manchester',
       'Manhattan', 'Medford', 'Melrose', 'Milwaukee Co.', 'Milton',
       'Minneapolis', 'Mobile', 'Montgomery', 'Niagara Falls', 'Muncie',
       'Muskegon', 'Needham', 'New Britain', 'New Castle', 'Newport News',
       'Philadelphia', 'Newton', 'Norfolk', 'Pontiac', 'Oakland',
       'Portland', 'Oshkosh', 'Richmond', 'Pittsburgh', 'Portsmouth',
       'Poughkeepsie', 'Quincy', 'Revere', 'Roanoke', 'Saginaw',
       'Rochester', 'Sacramento', 'Rockford', 'San Diego',
       'San Francisco', 'Spokane', 'Tacoma', 'Springfield', 'San Jose',
       'Schenectady', 'Saugus', 'Seattle', 'Syracuse', 'Terre Haute',
       'Somerville', 'SouthBend', 'St.Joseph', 'St.Louis',
       'St.Petersburg', 'Staten Island',
       'Stamford, Darien, and New Canaan', 'Stockton', 'Tampa', 'Toledo',
       'Troy', 'Trenton', 'Utica', 'Waltham', 'Warren', 'Wichita',
       'Watertown', 'Wheeling', 'Winchester', 'Winston Salem',
       'Youngstown', 'Winthrop']

}